name: Deploy to Staging
on:
  push:
    branches:
      - store
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to  Server
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸš€ Execute Deployment Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            echo "=== User Information ==="
            echo "Logged in as: $(whoami)"
            echo "Working directory: $(pwd)"
            echo "========================"
            cd /www/wwwroot/website_upgraded
            bash ./deploy_script.sh
